name:                error-or-utils
version:             0.2.0
synopsis:            Utilities using ErrorOr datatype
description:         Builds on the error type defined in the error-or package
homepage:            https://github.com/luntain/error-or-bundle/blob/master/error-or-utils#readme
license:             BSD3
author:              Kamil Dworakowski
maintainer:          kamil@dworakowski.name
copyright:           2020 Kamil Dworakowski
category:            data,library,testing
extra-source-files:
- README.md

tested-with: GHC == 8.0.2 || ==8.2.2 || ==8.6.5 || ==8.8.3 || ==8.10.2 || ==9.0.1 || ==9.2.1 || ==9.4.8 || ==9.6.6

dependencies:
  - base >= 4.7 && < 5
  - error-or >= 0.2.0.0
  - text
  - containers

library:
  source-dirs:      src
  ghc-options: -Wall -fno-warn-name-shadowing
