name:                error-or
version:             0.3.0
synopsis:            Composable, hierarchical errors.
description:         An Applicative Functor with error accumulation. Built in tree like error type
                     meant for gathering and reporting errors to users.
homepage:            https://github.com/luntain/error-or-bundle/blob/master/error-or#readme
license:             BSD3
author:              Kamil Dworakowski
maintainer:          kamil@dworakowski.name
copyright:           2020 Kamil Dworakowski
category:            data,library

extra-source-files:
- README.md
- changelog.md

tested-with: GHC == 8.0.2 || ==8.2.2 || ==8.6.5 || ==8.8.3 || ==8.10.2 || ==9.0.1 || ==9.2.1 || ==9.4.8 || ==9.6.6

dependencies:
  - base >= 4.9 && < 5 # Need base 4.9 due to Data.Semigroup and MonadFail
  - text
  - containers
  - mtl

library:
  source-dirs:      src
  ghc-options: -Wall -fno-warn-name-shadowing
